# Generated by Django 4.2.4 on 2023-08-22 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbbreviationReferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('abbreviation', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='BasicAverages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=45)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BoxTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.CharField(max_length=20)),
                ('flavor', models.CharField(max_length=3)),
                ('purchase_date', models.CharField(max_length=15)),
                ('price', models.IntegerField()),
                ('location', models.CharField(max_length=5)),
                ('started', models.CharField(max_length=15)),
                ('finished', models.CharField(max_length=15)),
                ('contributing', models.BooleanField()),
                ('filled', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CanData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=10)),
                ('initial_grams', models.IntegerField()),
                ('initial_floz', models.IntegerField()),
                ('final_grams', models.IntegerField()),
                ('final_floz', models.IntegerField()),
                ('finished', models.CharField(max_length=1)),
                ('percent_remaining_g', models.IntegerField()),
                ('percent_remaining_floz', models.IntegerField()),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.boxtracker')),
            ],
        ),
        migrations.CreateModel(
            name='BoxAverages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_grams', models.IntegerField()),
                ('initial_floz', models.IntegerField()),
                ('final_grams', models.IntegerField()),
                ('final_floz', models.IntegerField()),
                ('percent_remaining_g', models.IntegerField()),
                ('percent_remaining_floz', models.IntegerField()),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.boxtracker')),
            ],
        ),
    ]
