# Generated by Django 4.2.4 on 2023-11-14 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abbreviationreferences',
            name='category',
        ),
        migrations.AlterField(
            model_name='abbreviationreferences',
            name='uid',
            field=models.CharField(max_length=10),
        ),
    ]
