# Generated by Django 4.2.4 on 2023-11-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_abbreviationreferences_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxtracker',
            name='price',
            field=models.FloatField(),
        ),
    ]
