# Generated by Django 4.2.4 on 2023-11-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_boxtracker_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candata',
            name='cid',
            field=models.CharField(max_length=40),
        ),
    ]
