# Generated by Django 4.2.4 on 2024-01-07 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_candata_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxtracker',
            name='flavor',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='boxtracker',
            name='price',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='candata',
            name='final_floz',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='candata',
            name='final_grams',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='candata',
            name='finished',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='candata',
            name='initial_floz',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='candata',
            name='initial_grams',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='candata',
            name='percent_remaining_floz',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='candata',
            name='percent_remaining_g',
            field=models.CharField(max_length=5),
        ),
    ]
