# Generated by Django 4.2.4 on 2024-01-16 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_boxtracker_flavor_alter_boxtracker_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=10)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
